In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv(filepath_or_buffer="../data/raw/DataCoSupplyChainDataset.csv", encoding='latin-1')
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [3]:
df.shape # 53 Columns, 180519 Rows

(180519, 53)

In [4]:
df.info() # Dates are in str

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
cols = ['shipping date (DateOrders)', 'order date (DateOrders)']
df[cols] = df[cols].apply(pd.to_datetime)

In [7]:
(df.isnull().mean()*100).sort_values(ascending=False)

Product Description              100.000000
Order Zipcode                     86.239676
Customer Lname                     0.004432
Customer Zipcode                   0.001662
Days for shipment (scheduled)      0.000000
Sales per customer                 0.000000
Benefit per order                  0.000000
Delivery Status                    0.000000
Late_delivery_risk                 0.000000
Customer City                      0.000000
Customer Country                   0.000000
Category Id                        0.000000
Category Name                      0.000000
Customer Fname                     0.000000
Customer Email                     0.000000
Customer Password                  0.000000
Customer Id                        0.000000
Customer Segment                   0.000000
Customer State                     0.000000
Days for shipping (real)           0.000000
Type                               0.000000
Department Id                      0.000000
Customer Street                    0.000000
Department Name                    0.000000
Latitude                           0.000000
Order City                         0.000000
Order Country                      0.000000
Longitude                          0.000000
Market                             0.000000
Order Id                           0.000000
Order Item Cardprod Id             0.000000
Order Item Discount                0.000000
Order Item Discount Rate           0.000000
Order Item Id                      0.000000
Order Item Product Price           0.000000
Order Customer Id                  0.000000
order date (DateOrders)            0.000000
Order Item Quantity                0.000000
Order Item Profit Ratio            0.000000
Order Profit Per Order             0.000000
Sales                              0.000000
Order Region                       0.000000
Order State                        0.000000
Order Status                       0.000000
Order Item Total                   0.000000
Product Card Id                    0.000000
Product Category Id                0.000000
Product Image                      0.000000
Product Name                       0.000000
Product Price                      0.000000
Product Status                     0.000000
shipping date (DateOrders)         0.000000
Shipping Mode                      0.000000
dtype: float64

In [8]:
print(df['Customer Email'].value_counts())

print(df['Customer Password'].value_counts())

print(df['Product Image'].value_counts())

Customer Email
XXXXXXXXX    180519
Name: count, dtype: int64
Customer Password
XXXXXXXXX    180519
Name: count, dtype: int64
Product Image
http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck                                 24515
http://images.acmesports.sports/Nike+Men%27s+CJ+Elite+2+TD+Football+Cleat                        22246
http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo                           21035
http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest                             19298
http://images.acmesports.sports/Field+%26+Stream+Sportsman+16+Gun+Fire+Safe                      17325
                                                                                                 ...
http://images.acmesports.sports/Stiga+Master+Series+ST3100+Competition+Indoor+Table+Tennis...       27
http://images.acmesports.sports/SOLE+E35+Elliptical                                                 15
http://images.acmesports.sports/Bushnell+Pro+X7+Jolt+Slope+Rangefinder                              11
http://images.acmesports.sports/SOLE+E25+Elliptical                                                 10
http://images.acmesports.sports/Bowflex+SelectTech+1090+Dumbbells                                   10
Name: count, Length: 118, dtype: int64

In [9]:
df[df['Customer City'] == 'CA']

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
35704,DEBIT,2,1,66.379997,189.660004,Late delivery,1,65,Consumer Electronics,CA,EE. UU.,XXXXXXXXX,Sara,14577,Foreman,XXXXXXXXX,Consumer,95758,Elk Grove,NaN,10,Technology,39.134159,-123.718552,Europe,Valence,Francia,14577,2017-11-02 18:31:00,71024,1352,63.220001,0.25,174339,252.880005,0.35,1,252.880005,189.660004,66.379997,Western Europe,Auvernia-Ródano-Alpes,COMPLETE,NaN,1352,65,NaN,http://images.acmesports.sports/Industrial+con...,Industrial consumer electronics,252.880005,0,2017-11-04 18:31:00,First Class
46440,PAYMENT,4,4,10.910000,38.959999,Shipping on time,0,75,Video Games,CA,EE. UU.,XXXXXXXXX,Eugenia,17171,Slater,XXXXXXXXX,Corporate,95758,Elk Grove,NaN,9,Discs Shop,38.408573,-121.449112,Pacific Asia,Manila,Filipinas,17171,2017-12-10 15:18:00,73618,1362,0.800000,0.02,176933,39.750000,0.28,1,39.750000,38.959999,10.910000,Southeast Asia,Capital Nacional,PENDING_PAYMENT,NaN,1362,75,NaN,http://images.acmesports.sports/Fighting+video...,Fighting video games,39.750000,0,2017-12-14 15:18:00,Standard Class
82511,DEBIT,4,4,59.990002,299.959992,Shipping on time,0,63,Children's Clothing,CA,EE. UU.,XXXXXXXXX,Zena,14046,Elliott,XXXXXXXXX,Consumer,91732,El Monte,NaN,4,Apparel,34.071892,-118.013886,Europe,Sheffield,Reino Unido,14046,2017-10-26 00:29:00,70493,1350,57.139999,0.16,173808,357.100006,0.20,1,357.100006,299.959992,59.990002,Northern Europe,Inglaterra,COMPLETE,NaN,1350,63,NaN,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,2017-10-30 00:29:00,Standard Class

In [10]:
df['Customer Zipcode'] = df['Customer Zipcode'].astype('str')

df.loc[df['Customer State'] == '95758', 'Customer Zipcode'] = '95758'
df.loc[df['Customer State'] == '91732', 'Customer Zipcode'] = '91732'

df.loc[df['Customer State'] == '95758', 'Customer City'] = 'Unknown'
df.loc[df['Customer State'] == '91732', 'Customer City'] = 'Unknown'

df.loc[df['Customer State'] == '95758', 'Customer State'] = 'CA'
df.loc[df['Customer State'] == '91732', 'Customer State'] = 'CA'

In [11]:
df[df['Customer Zipcode'].isnull()]

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Order Zipcode, Product Card Id, Product Category Id, Product Description, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

In [12]:
drop_cols = ['Product Description', 'Order Zipcode', 'Customer Email', 'Customer Password', 'Product Image', 'Customer Street']
df.drop(drop_cols, axis=1, inplace=True)

df['Customer Lname'] = df['Customer Lname'].fillna('Unknown')

In [13]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Department Id,Latitude,Longitude,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Card Id,Product Category Id,Product Price,Product Status,shipping date (DateOrders)
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.0,180519
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,5.443460,29.719955,-84.915675,6691.379495,2016-06-12 17:47:04.669868,36221.894903,692.509764,20.664741,0.101668,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,692.509764,31.851451,141.232550,0.0,2016-06-16 05:45:23.202433
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,2.000000,-33.937553,-158.025986,1.000000,2015-01-01 00:00:00,1.000000,19.000000,0.000000,0.000000,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,19.000000,2.000000,9.990000,0.0,2015-01-03 00:00:00
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,4.000000,18.265432,-98.446312,3258.500000,2015-09-21 13:49:00,18057.000000,403.000000,5.400000,0.040000,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,403.000000,18.000000,50.000000,0.0,2015-09-25 06:59:00
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,5.000000,33.144863,-76.847908,6457.000000,2016-06-11 13:06:00,36140.000000,627.000000,14.000000,0.100000,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,627.000000,29.000000,59.990002,0.0,2016-06-15 08:32:00
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,7.000000,39.279617,-66.370583,9779.000000,2017-03-01 08:42:00,54144.000000,1004.000000,29.990000,0.160000,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,1004.000000,45.000000,199.990005,0.0,2017-03-04 21:29:00
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,12.000000,48.781933,115.263077,20757.000000,2018-01-31 23:38:00,77204.000000,1363.000000,500.000000,0.250000,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,1363.000000,76.000000,1999.989990,0.0,2018-02-06 22:14:00
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,1.629246,9.813646,21.433241,4162.918106,NaN,21045.379569,336.446807,21.800901,0.070415,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,336.446807,15.640064,139.732492,0.0,NaN

In [14]:
df[['Benefit per order', 'Order Profit Per Order']] # Duplicate columns

        Benefit per order  Order Profit Per Order
0               91.250000               91.250000
1             -249.089996             -249.089996
2             -247.779999             -247.779999
3               22.860001               22.860001
4              134.210007              134.210007
...                   ...                     ...
180514          40.000000               40.000000
180515        -613.770019             -613.770019
180516         141.110001              141.110001
180517         186.229996              186.229996
180518         168.949997              168.949997

[180519 rows x 2 columns]

In [15]:
df['Product Status'] # Dead Column

0         0
1         0
2         0
3         0
4         0
         ..
180514    0
180515    0
180516    0
180517    0
180518    0
Name: Product Status, Length: 180519, dtype: int64

In [16]:
df.drop(['Benefit per order', 'Product Status'], axis=1, inplace=True)

In [17]:
df['Lead_Time_Deviation'] = df['Days for shipping (real)'] - df['Days for shipment (scheduled)']
print(df[['Lead_Time_Deviation', 'Late_delivery_risk']])

        Lead_Time_Deviation  Late_delivery_risk
0                        -1                   0
1                         1                   1
2                         0                   0
3                        -1                   0
4                        -2                   0
...                     ...                 ...
180514                    0                   0
180515                    1                   1
180516                    1                   1
180517                   -1                   0
180518                    0                   0

[180519 rows x 2 columns]

In [18]:
pd.crosstab(df['Delivery Status'], df['Lead_Time_Deviation'])

Lead_Time_Deviation     -2     -1      0      1      2     3     4
Delivery Status
Advance shipping     20873  20719      0      0      0     0     0
Late delivery            0      0      0  57957  27551  6772  6697
Shipping canceled      793    981   1557   2690   1167   280   286
Shipping on time         0      0  32196      0      0     0     0

In [19]:
pd.crosstab(df['Late_delivery_risk'], df['Lead_Time_Deviation'])

Lead_Time_Deviation     -2     -1      0      1      2     3     4
Late_delivery_risk
0                    21666  21700  33753   2690   1167   280   286
1                        0      0      0  57957  27551  6772  6697

In [20]:
pd.crosstab(df['Late_delivery_risk'], df['Delivery Status'])

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Late_delivery_risk,,,,
0,41592,0,7754,32196
1,0,98977,0,0

In [21]:
cont_num_cols = [col for col in df.columns if df[col].dtype == 'float64']
disc_num_cols = [col for col in df.columns if df[col].dtype == 'int64']
cat_cols = [col for col in df.columns if df[col].dtype == 'str']

In [22]:
for col in disc_num_cols:
    print(df[col].value_counts())
    print()

Days for shipping (real)
2    56618
3    28765
6    28723
4    28513
5    28163
0     5080
1     4657
Name: count, dtype: int64

Days for shipment (scheduled)
4    107752
2     35216
1     27814
0      9737
Name: count, dtype: int64

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Category Id
17    24551
18    22246
24    21035
46    19298
45    17325
48    15540
43    13729
9     12487
29    10984
37     2029
40     1780
36     1475
26     1201
13     1127
35     1070
41      974
75      838
63      652
76      650
3       632
7       614
62      592
74      529
33      524
72      492
66      484
68      484
67      483
64      442
32      441
44      440
71      434
65      431
12      423
59      405
38      384
69      362
73      357
5       343
6       328
11      309
30      283
61      271
70      208
60      207
31      181
2       138
10      111
16       68
4        67
34       61
Name: count, dtype: int64

Customer Id
5654     47
10591    45
5004     45
9371     44
3708     44
         ..
18586     1
16322     1
18579     1
16244     1
2677      1
Name: count, Length: 20652, dtype: int64

Department Id
7     66861
4     48998
5     33220
3     14525
6      9686
2      2479
9      2026
10     1465
11      492
8       405
12      362
Name: count, dtype: int64

Order Customer Id
5654     47
10591    45
5004     45
9371     44
3708     44
         ..
18586     1
16322     1
18579     1
16244     1
2677      1
Name: count, Length: 20652, dtype: int64

Order Id
45461    5
31115    5
47752    5
17162    5
64813    5
        ..
26806    1
26773    1
26463    1
26327    1
26118    1
Name: count, Length: 65752, dtype: int64

Order Item Cardprod Id
365     24515
403     22246
502     21035
1014    19298
1004    17325
        ...
127        27
208        15
860        11
60         10
226        10
Name: count, Length: 118, dtype: int64

Order Item Id
180517    1
179254    1
179253    1
179252    1
179251    1
         ..
65177     1
65161     1
65129     1
65126     1
65113     1
Name: count, Length: 180519, dtype: int64

Order Item Quantity
1    99134
5    20385
3    20350
4    20335
2    20315
Name: count, dtype: int64

Product Card Id
365     24515
403     22246
502     21035
1014    19298
1004    17325
        ...
127        27
208        15
860        11
60         10
226        10
Name: count, Length: 118, dtype: int64

Product Category Id
17    24551
18    22246
24    21035
46    19298
45    17325
48    15540
43    13729
9     12487
29    10984
37     2029
40     1780
36     1475
26     1201
13     1127
35     1070
41      974
75      838
63      652
76      650
3       632
7       614
62      592
74      529
33      524
72      492
66      484
68      484
67      483
64      442
32      441
44      440
71      434
65      431
12      423
59      405
38      384
69      362
73      357
5       343
6       328
11      309
30      283
61      271
70      208
60      207
31      181
2       138
10      111
16       68
4        67
34       61
Name: count, dtype: int64

Lead_Time_Deviation
 1    60647
 0    33753
 2    28718
-1    21700
-2    21666
 3     7052
 4     6983
Name: count, dtype: int64

In [23]:
# Proving that these are duplicate columns

# df[['Customer Id', 'Order Customer Id']]

# df[['Order Item Cardprod Id', 'Product Card Id']]

# df[['Category Id', 'Product Category Id']]

drop_cols = ['Order Customer Id', 'Order Item Cardprod Id', 'Category Id']
df.drop(drop_cols, axis=1, inplace=True)

In [24]:
for col in cont_num_cols:
    print(df[col].value_counts())
    print()

Sales per customer
122.839996     1264
109.190002     1247
127.389999     1243
118.290001     1243
116.989998     1243
               ...
1939.989990       1
84.150002         1
298.769989        1
403.709992        1
474.760010        1
Name: count, Length: 2927, dtype: int64

Latitude
18.227573    417
39.495914    370
18.227577    300
36.910831    280
26.098499    270
            ...
18.261518      1
18.223066      1
18.240482      1
18.261297      1
18.242485      1
Name: count, Length: 11250, dtype: int64

Longitude
-66.370613    3821
-66.370575    3523
-66.370590    3522
-66.370506    3465
-66.370552    3417
              ...
-85.721458       1
-73.406136       1
-87.624718       1
-92.192482       1
-81.288292       1
Name: count, Length: 4487, dtype: int64

Order Item Discount
0.000000      10028
6.000000       4589
12.000000      4067
4.000000       3647
8.000000       3626
              ...
50.490002         1
85.489998         1
140.000000        1
33.660000         1
61.189999         1
Name: count, Length: 1017, dtype: int64

Order Item Discount Rate
0.04    10029
0.05    10029
0.06    10029
0.07    10029
0.09    10029
0.10    10029
0.12    10029
0.13    10029
0.15    10029
0.16    10029
0.17    10029
0.18    10029
0.20    10029
0.25    10029
0.03    10029
0.00    10028
0.01    10028
0.02    10028
Name: count, dtype: int64

Order Item Product Price
59.990002      24820
129.990005     22372
50.000000      21035
49.980000      19298
399.980011     17325
               ...
349.989990        40
329.989990        27
599.989990        21
1999.989990       15
999.989990        10
Name: count, Length: 75, dtype: int64

Order Item Profit Ratio
 0.48    9197
 0.35    7997
 0.26    6577
 0.34    6507
 0.47    6378
         ...
-2.45      18
-0.93      18
-0.90      18
-2.30      18
-2.10      18
Name: count, Length: 162, dtype: int64

Sales
129.990005    22372
399.980011    17325
199.990005    15622
299.980011    13729
179.970001     5016
              ...
999.989990       10
379.959992       10
198.000000        9
396.000000        9
99.000000         9
Name: count, Length: 193, dtype: int64

Order Item Total
122.839996     1264
109.190002     1247
127.389999     1243
118.290001     1243
116.989998     1243
               ...
1939.989990       1
84.150002         1
298.769989        1
403.709992        1
474.760010        1
Name: count, Length: 2927, dtype: int64

Order Profit Per Order
 0.000000      1177
 143.990005     199
 72.000000      194
 46.799999      188
 24.000000      181
               ...
-569.169983       1
-246.490005       1
-103.970001       1
-237.589996       1
-337.100006       1
Name: count, Length: 21998, dtype: int64

Product Price
59.990002      24820
129.990005     22372
50.000000      21035
49.980000      19298
399.980011     17325
               ...
349.989990        40
329.989990        27
599.989990        21
1999.989990       15
999.989990        10
Name: count, Length: 75, dtype: int64

In [25]:
# Proving that these are duplicate columns

# df[['Order Item Total', 'Sales per customer']]

# df[['Order Item Product Price', 'Product Price']]

drop_cols = ['Order Item Total', 'Order Item Product Price']
df.drop(drop_cols, axis=1, inplace=True)

In [26]:
for col in cat_cols:
    print(df[col].value_counts())
    print()

Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Cameras                   592
Toys                      529
Golf Shoes                524
Pet Supplies              492
Crafts                    484
Garden                    484
DVDs                      483
Computers                 442
Golf Apparel              441
Hunting & Shooting        440
Music                     434
Consumer Electronics      431
Boxing & MMA              423
Books                     405
Kids' Golf Clubs          384
Health and Beauty         362
Sporting Goods            357
Lacrosse                  343
Tennis & Racquet          328
Fitness Accessories       309
Men's Golf Clubs          283
CDs                       271
Men's Clothing            208
Baby                      207
Women's Golf Clubs        181
Soccer                    138
Strength Training         111
As Seen on  TV!            68
Basketball                 67
Golf Bags & Carts          61
Name: count, dtype: int64

Customer City
Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
               ...
Bartlett          25
Ponce             22
Malden            22
Freehold          13
Unknown            3
Name: count, Length: 563, dtype: int64

Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

Customer Fname
Mary       65150
James       1835
Robert      1759
Michael     1680
David       1625
           ...
Le             1
Huff           1
Beatty         1
Paola          1
Brees          1
Name: count, Length: 782, dtype: int64

Customer Lname
Smith       64104
Johnson       989
Brown         909
Williams      869
Jones         859
            ...
Guevara         1
Alexan          1
Kiney           1
Delan           1
Harri           1
Name: count, Length: 1110, dtype: int64

Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

Customer State
PR    69373
CA    29226
NY    11327
TX     9103
IL     7631
FL     5456
OH     4095
PA     3824
MI     3804
NJ     3191
AZ     3026
GA     2503
MD     2415
NC     1992
CO     1914
VA     1849
OR     1668
MA     1607
TN     1582
NV     1440
MO     1354
HI     1248
CT     1094
UT      968
NM      949
LA      948
WA      920
WI      850
MN      672
SC      665
IN      581
DC      579
KY      487
KS      458
DE      269
RI      243
WV      241
OK      232
ND      215
ID      167
AR      164
MT       87
IA       67
AL       35
Name: count, dtype: int64

Customer Zipcode
725.0      66770
921.0        337
23455.0      334
957.0        297
79109.0      292
           ...
32210.0       15
7728.0        13
11225.0        9
95758          2
91732          1
Name: count, Length: 997, dtype: int64

Department Name
Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: count, dtype: int64

Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

Order City
Santo Domingo           2211
New York City           2202
Los Angeles             1845
Tegucigalpa             1783
Managua                 1682
                        ...
Limbe                      1
Campo Limpo Paulista       1
Tottori                    1
Yucaipa                    1
Pico Rivera                1
Name: count, Length: 3597, dtype: int64

Order Country
Estados Unidos       24840
Francia              13222
México               13172
Alemania              9564
Australia             8497
                     ...
Guinea Ecuatorial        2
Kuwait                   2
Sáhara Occidental        2
Burundi                  1
Serbia                   1
Name: count, Length: 164, dtype: int64

Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
                               ...
Terranova                         1
Bitola                            1
Savanes                           1
Bistrita-Nasaud                   1
Tottori                           1
Name: count, Length: 1089, dtype: int64

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

Product Name
Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
                                                 ...
Stiga Master Series ST3100 Competition Indoor       27
SOLE E35 Elliptical                                 15
Bushnell Pro X7 Jolt Slope Rangefinder              11
SOLE E25 Elliptical                                 10
Bowflex SelectTech 1090 Dumbbells                   10
Name: count, Length: 118, dtype: int64

Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [27]:
# print(df['Delivery Status'].value_counts()) # Fine

# print(df['Shipping Mode'].value_counts()) # Fine

# print(df['Customer Segment'].value_counts()) # Fine

print(df['Order Region'].value_counts())

Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

In [28]:
region_cleaning_map = {
    "South of  USA": "South US",  # Fixes the double-space typo natively
    "West of USA": "West US",
    "East of USA": "East US",
    "US Center": "Central US"
}

df['Order Region'] = df['Order Region'].str.strip()
df['Order Region'] = df['Order Region'].replace(region_cleaning_map)

In [29]:
print(df['Order Region'].value_counts())

Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West US             7993
South Asia          7731
Eastern Asia        7280
East US             6915
West Asia           6009
Central US          5887
South US            4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

In [30]:
country_translation = {
    'EE. UU.': 'United States',
    'Estados Unidos': 'United States',
    'Francia': 'France',
    'Alemania': 'Germany',
    'México': 'Mexico',
    'Australia': 'Australia'
    # Add other explicit translations as needed based on your unique values
}

# Apply mapping with a fallback to the original name if it's not in the dictionary
df['Customer Country'] = df['Customer Country'].map(country_translation).fillna(df['Customer Country'])
df['Order Country'] = df['Order Country'].map(country_translation).fillna(df['Order Country'])

In [31]:
print(df['Order Country'].value_counts())

Order Country
United States        24840
France               13222
Mexico               13172
Germany               9564
Australia             8497
                     ...
Guinea Ecuatorial        2
Kuwait                   2
Sáhara Occidental        2
Burundi                  1
Serbia                   1
Name: count, Length: 164, dtype: int64

In [32]:
df[df['Customer City'] == 'Unknown']

,Type,Days for shipping (real),Days for shipment (scheduled),Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,order date (DateOrders),Order Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Profit Ratio,Order Item Quantity,Sales,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Lead_Time_Deviation
35704,DEBIT,2,1,189.660004,Late delivery,1,Consumer Electronics,Unknown,United States,Sara,14577,Foreman,Consumer,CA,95758,10,Technology,39.134159,-123.718552,Europe,Valence,France,2017-11-02 18:31:00,71024,63.220001,0.25,174339,0.35,1,252.880005,66.379997,Western Europe,Auvernia-Ródano-Alpes,COMPLETE,1352,65,Industrial consumer electronics,252.880005,2017-11-04 18:31:00,First Class,1
46440,PAYMENT,4,4,38.959999,Shipping on time,0,Video Games,Unknown,United States,Eugenia,17171,Slater,Corporate,CA,95758,9,Discs Shop,38.408573,-121.449112,Pacific Asia,Manila,Filipinas,2017-12-10 15:18:00,73618,0.800000,0.02,176933,0.28,1,39.750000,10.910000,Southeast Asia,Capital Nacional,PENDING_PAYMENT,1362,75,Fighting video games,39.750000,2017-12-14 15:18:00,Standard Class,0
82511,DEBIT,4,4,299.959992,Shipping on time,0,Children's Clothing,Unknown,United States,Zena,14046,Elliott,Consumer,CA,91732,4,Apparel,34.071892,-118.013886,Europe,Sheffield,Reino Unido,2017-10-26 00:29:00,70493,57.139999,0.16,173808,0.20,1,357.100006,59.990002,Northern Europe,Inglaterra,COMPLETE,1350,63,Children's heaters,357.100006,2017-10-30 00:29:00,Standard Class,0

In [33]:
customer_cols = ["Customer Id", "Customer Segment", "Customer Fname", "Customer Lname", "Customer Email", "Customer Password", "Customer Street", "Customer Zipcode", "Customer City", "Customer State", "Customer Country", "Latitude", "Longitude"]
products_cols = ["Product Card Id", "Product Category Id", "Department Id", "Product Name", "Product Description",	"Product Image", "Product Price", "Product Status"]
product_category_cols = ["Category Id", "Category Name"]
product_department_cols = ["Department Id", "Department Name"]
order_header_cols = ["Order Id", "Order Customer Id", "Type","Order Profit Per Order", "Benefit per order",
                     "Shipping Mode", "Days for shipping (real)", "Days for shipment (scheduled)",
                     "order date (DateOrders)", "shipping date (DateOrders)", "Delivery Status",
                     "Order Status", "Late_delivery_risk", "Sales per customer",
                     "Market", "Order Region", "Order Country", "Order State", "Order City", "Order Zipcode"]
order_lineitem_cols = ["Order Item Id", "Order Item Cardprod Id", "Order Item Quantity",
                       "Order Item Product Price", "Order Item Discount Rate", "Order Item Discount", 
                       "Order Item Total", "Order Item Profit Ratio", "Sales"]
geo_cols = ["Market", "Order Region", "Order Country", "Order State", "Order City", "Order Zipcode"]

customer_table = df[customer_cols]
product_table = df[products_cols]
product_category_table = df[product_category_cols]
product_department_table = df[product_department_cols]
orders_header_table = df[order_header_cols]
orders_lineitem_table = df[order_lineitem_cols]
geo_table = df[geo_cols]

KeyError: "['Customer Email', 'Customer Password', 'Customer Street'] not in index"